spring.application.name=PaymentService

server.port=${SERVER_PORT:8080}

spring.mvc.problemdetails.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# PostgreSQL / JPA / Flyway
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.01:5432/payment_service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:payment}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:payment}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

# Kafka producer
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:49092}
spring.kafka.template.default-topic=${PAYMENT_EVENT_TOPIC:payment-events}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.spring.json.add.type.headers=false
payment.kafka.payment-event-topic=${PAYMENT_EVENT_TOPIC:payment-events}